<?php
/**
 *
 * NOTICE OF LICENSE
 *
 * Todos direitos reservados para Thirdlevel | ThirdLevel All Rights Reserved
 *
 * @company   	ThirdLevel
 * @package    	MercadoLivre
 * @author      André Fuhrman (andrefuhrman@gmail.com)
 * @copyright  	Copyright (c) ThirdLevel [http://www.thirdlevel.com.br]
 *
 */
$code = $this->getCode();
?>

<iframe src="https://painel.plugg.to/user/auto/<?php echo $code; ?>" 
    width="100%" height="100%" style="position: absolute; height: 100%; border: none; z-index:9999" 
    frameborder="0" scrolling="auto"></iframe>